blog/app_blog/urls.py
from django.urls import path
from app_blog import views

app_name='app_blog'

urlpatterns=[
    path('', views.BlogList.as_view(), name='blog_list'),
    path('create_blog/',views.CreateBlog.as_view(),name='create_blog'),
    path('blog_details/<str:slug>',views.blog_details,name='blog_details'),
    path('my_predictions/',views.prediction_form, name='my_predictions'),



]

blog/app_login/urls.py
from django.urls import path
from app_login import views

app_name='app_login'

urlpatterns=[
    path('signup_form/',views.signup_form, name='signup_form' ),
    path('login_page/',views.login_page, name='login_page' ),
    path('logout_page/',views.logout_page,name='logout_page'),
    path('User_profile/',views.User_profile,name='User_profile'),
    path('user_change/',views.user_change,name='user_change'),
    path('profile_pics/',views.profile_pics,name='profile_pics'),
    path('change_profile_pics/',views.change_profile_pics,name='change_profile_pics'),

    
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static


# the array name of urlpatterns and the apps.urls.py files array name of urlpattern have to be same
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('app_login.urls',namespace='app_login')),
    path('blog/',include('app_blog.urls',namespace='app_blog')),
    path('',views.Index, name='index'),
    

]



# To Add Media files, or upload media files to a direction, below two lines must be added
urlpatterns=urlpatterns+staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/templates/base.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
    <title> {% block title_block %} Blogs {% endblock %}

    </title>

</head>
 <body>
     <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
         <ul class="navbar-nav">
             <li class="nav-item active" >
                 <a class="nav-link" href="{% url 'index' %}"> 

                    
                    <img src="/media/home_page.png" width="50px">
                    </a>
             </li>
             {% if user.is_authenticated %}
             <li class="nav-item active" >
                <a class="nav-link" href="{% url 'app_login:User_profile' %}"> 
                   Your Profile</a>
            </li>  

            <li class="nav-item active" >
                <a class="nav-link" href="{% url 'app_blog:create_blog' %}"> 
                   Write Blog</a>
            </li>
            <li class="nav-item active" >
                <a class="nav-link" href="{% url 'app_blog:my_predictions' %}"> 
                   Try Predictions!! </a>
            </li>

            <li class="nav-item active" >
                <a class="nav-link" href="{% url 'app_blog:chat' %}"> 
                   Chat With Me!! </a>
            </li>
            

              

             <li class="nav-item active" >
                <a class="nav-link" href="{% url 'app_login:logout_page' %}" > 
                   Logout </a>
            </li>

           
             {% else %}
             <li class="nav-item active" >
                <a class="nav-link" href="{% url 'app_login:login_page' %}"> 
                   Login</a>
            </li>
            <li>
            <a class="nav-link" href="{% url 'app_login:signup_form' %}"> 
                Signup</a>
            </li>
            
            {% endif %}

         </ul>
     </nav>

     <div class="container" style="padding-top:20px">
        {% block body_block%}
{% endblock%}

    </div>
</body>
</html>