blog/app_login/urls.py
from django.urls import path
from app_login import views

app_name='app_login'

urlpatterns=[
    path('signup_form/',views.signup_form, name='signup_form' ),
    path('login_page/',views.login_page, name='login_page' ),
    path('logout_page/',views.logout_page,name='logout_page'),
    path('User_profile/',views.User_profile,name='User_profile'),
    path('user_change/',views.user_change,name='user_change'),
    path('profile_pics/',views.profile_pics,name='profile_pics'),
    path('change_profile_pics/',views.change_profile_pics,name='change_profile_pics'),

    
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static


# the array name of urlpatterns and the apps.urls.py files array name of urlpattern have to be same
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('app_login.urls',namespace='app_login')),
    path('blog/',include('app_blog.urls',namespace='app_blog')),
    path('',views.Index, name='index'),
    

]



# To Add Media files, or upload media files to a direction, below two lines must be added
urlpatterns=urlpatterns+staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#related_name field is mainly used to access particular data field directly from a table without using QUERY
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile',on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='user_pics/')

blog/app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from app_login.models import UserProfile

class Signup_form(UserCreationForm):
    email = forms.EmailField(label='Email Address',required=True)
    class Meta: 
        model= User
        fields = ('username','email','password1','password2')

class User_change(UserChangeForm):
    class Meta:
        model= User
        fields = ('username','email','first_name','last_name','password')


class profile_pic(forms.ModelForm):
    class Meta:
        model= UserProfile
        fields= ['profile_pic', ]

blog/app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required 
from app_login.forms import Signup_form, User_change, profile_pic

# Create your views here.
def signup_form(request):
    forms=Signup_form()
    registered = False
    if request.method == 'POST':
        forms = Signup_form(data=request.POST)
        if forms.is_valid():
            forms.save(commit=True)
            registered = True
    diction={'forms':forms, 'registered':registered}
    return render(request, 'app_login/signup.html',context=diction)

def login_page(request):
    forms= AuthenticationForm()
    if request.method=='POST':
        forms = AuthenticationForm(data=request.POST)

        if forms.is_valid():
            username= forms.cleaned_data.get('username') # if form is noT Valid, YOU cannot get cleaned data
            password = forms.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    diction={'forms':forms}
    return render(request,'app_login/login.html',context=diction)

@login_required
def logout_page(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def User_profile(request):
    return render(request, 'app_login/user_profile.html',context={})


@login_required
def user_change(request):
    current_user = request.user
    form= User_change(instance=current_user) # To get the info of Current Info of the USer
    if request.method== 'POST':
        form = User_change(request.POST, instance=current_user) #(value which will be used, value which will be changed)
        if form.is_valid():
            form.save()
            form = User_change(instance=current_user) # To Showed the latest Changed Value of User
    return render(request,'app_login/user_change.html',context={'form':form})

@login_required
def profile_pics(request):
    forms= profile_pic()
    if request.method=='POST':
        forms=profile_pic(request.POST,request.FILES) # while uploading file, request.FILES has to be added
        if forms.is_valid():
            user_obj = forms.save(commit=False)
            user_obj.user =request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:User_profile'))
            # reverse(app_name: 'name' of the html page which is given in urls.py)

    return render(request, 'app_login/profile_pics.html',context={'forms':forms})

@login_required
def change_profile_pics(request):
    forms=profile_pic(instance=request.user.user_profile)
    if request.method=='POST':
        forms=profile_pic(request.POST,request.FILES,instance=request.user.user_profile ) # while uploading file, request.FILES has to be added
        if forms.is_valid():
            user_obj = forms.save(commit=False)
            user_obj.user =request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:User_profile'))
            # reverse(app_name: 'name' of the html page which is given in urls.py)
    return render(request, 'app_login/profile_pics.html',context={'forms':forms})
    
        

blog/templates/app_login/login.html
{%extends 'base.html' %}
{% load crispy_forms_tags%}
{% block title_block %}Login Page{% endblock %}

{% block body_block %}
<h2> Login </h2>
<form method="POST">
    {{forms|crispy}}
    {%  csrf_token %}
<button type="submit" class="btn btn-success btn-sm">
    Login
</button>

</form>
{% endblock %}

blog/templates/app_login/profile_pics.html
{%extends 'base.html' %}
{% load crispy_forms_tags%}
{% block title_block %}Profile Picture Change{% endblock %}

{% block body_block %}
<h2>Change Picture </h2>
<form method="POST" enctype="multipart/form-data">
    {{ forms|crispy }}
    {%  csrf_token %}
<button type="submit" class="btn btn-success btn-sm">
    Upload
</button>

</form>
{% endblock %}

blog/templates/app_login/signup.html
{%extends 'base.html' %}
{% load crispy_forms_tags%}
{% block title_block %}

Signup Page

{% endblock %}


{% block body_block %}
{% if registered %}
<div class="alert alert-success">
    Account Created Successfully!!!
     <a href="{% url 'app_login:login_page'%}">
        Login Here!
     </a>
    </div>
{% else %}
<h2> Create New Account! </h2>
<form method="POST"> 
    
{{ forms|crispy }}
{%  csrf_token %}
<button type="submit" class="btn btn-danger btn-sm">
    Create Account
</button>

</form>

<br>
<p>
    Already Have An Account!?
    <a href="{% url 'app_login:login_page'%}"> Login Here
</a>
</p>
{% endif%}
{% endblock %}

blog/templates/app_login/user_change.html
{%extends 'base.html' %}
{% load crispy_forms_tags%}
{% block title_block %}User Profile Edit{% endblock %}

{% block body_block %}
<h2> Your Profile</h2>
<form method="POST">
    {{form|crispy}}
    {%  csrf_token %}
<button type="submit" class="btn btn-success btn-sm">
    Save
</button>

</form>
<p> <a  href="{% url 'app_login:User_profile'%}" > Your Profile </a> </p>
{% endblock %}

blog/templates/app_login/user_profile.html
{%extends 'base.html' %}
{% block title_block %}User Profile Page{% endblock %}

{% block body_block %}
<h2> Your Profile</h2>
{% if user.user_profile %}  <!-- here user_profile is the related name filed from the models-->
<img src="/media/{{user.user_profile.profile_pic}}" class="img-thumbnail" width="200px">
<br>
<a href="{%url 'app_login:change_profile_pics'%}"> <button type="submit" class="btn btn-danger btn-sm" >
     Change Profile Picture
 </button></a>
{%else%}
<img src="/media/user_pics/no_profile_avatar.jpg" class="rounded-circle" width="200px">
<br>
<a href="{%url 'app_login:profile_pics'%}"> <button type="submit" class="btn btn-danger btn-sm" >
     Change Profile Picture
 </button></a>
{% endif %}

<p> Email: {{user.email}} </p>
<p> UserName: {{user.username}}   </p>
<p> Name:  {{user.first_name}} {{user.last_name}}</p>
<p> <a href="{% url 'app_login:user_change' %}"> Edit Profile Info </a> 
     </p>


{% endblock %}